export const categoryList = [
  {
    id: 1,
    value: 'M',
    label: 'Men',
  },
  {
    id: 2,
    value: 'W',
    label: 'Women',
  },
];

export const ratingList = [
  {
    id: 1,
    value: '1',
    label: '1🌟',
  },
  {
    id: 2,
    value: '2',
    label: '2🌟',
  },
  {
    id: 3,
    value: '3',
    label: '3🌟',
  },
  {
    id: 4,
    value: '4',
    label: '4🌟',
  },
  {
    id: 5,
    value: '5',
    label: '5🌟',
  },
];

export const dataList = [
  {
    id: 1,
    title: 'Mid Formal Shirt', 
    category: 'M',
    color: 'blue',
    rating: 5,
    price: 2500,
    coverSrc: 'images/list/img1.jpg',
  },
  {
    id: 2,
    title: 'Bandhgala',
    category: 'M',
    color: 'blue',
    rating: 4,
    price: 1000,
    coverSrc: 'images/list/img1.webp',
  },
  {
    id: 3,
    title: 'Slim Fit Tshirt',
    category: 'M',
    color: 'blue',
    rating: 3,
    price: 2000,
    coverSrc: 'images/list/img2.png',
  },
  {
    id: 4,
    title: 'Casual Grey Tshirt',
    category: 'M',
    color: 'grey',
    rating: 1,
    price: 1800,
    coverSrc: 'images/list/img3.jpg',
  },
  {
    id: 5,
    title: 'Lavender Tshirt',
    category: 'W',
    color: 'purple',
    rating: 2,
    price: 4100,
    coverSrc: 'images/list2/w3.jpg',
  },
  {
    id: 6,
    title: 'Casual Blue Tshirt',
    category: 'M',
    color: 'blue',
    rating: 5,
    price: 2000,
    coverSrc: 'images/list/img4.jpg',
  },
  {
    id: 7,
    title: 'lose fit tshirt',
    category: 'M',
    color: 'blue',
    rating: 5,
    price: 3500,
    coverSrc: 'images/list/img5.png',
  },
  {
    id: 8,
    title: 'Full Sleeves tshirt',
    category: 'M',
    color: 'grey',
    rating: 2,
    price: 2200,
    coverSrc: 'images/list/img6.jpeg',
  },
  {
    id: 9,
    title: 'Black Full Sleeves',
    category: 'M',
    color: 'black',
    rating: 1,
    price: 1900,
    coverSrc: 'images/list/img7.jpg',
  },
  {
    id: 10,
    title: 'Red Casual Tshirt',
    category: 'M',
    color: 'red',
    rating: 4,
    price: 2750,
    coverSrc: 'images/list/img8.jpg',
  },
  {
    id: 11,
    title: 'Army Print Tshirt',
    category: 'W',
     color: 'green',
    rating: 2,
    price: 4350,
    coverSrc: 'images/list2/w5.webp',
  },
  {
    id: 12,
    title: 'Women yellow casual',
    category: 'W',
    color: 'yellow',
    rating: 3,
    price: 3300,
    coverSrc: 'images/list2/w2.jpg',
  },

];
